apiVersion: batch/v1
kind: CronJob
metadata:
  name: chaos-engineering
  namespace: sre-challenge
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: chaos-engineering
              image: busybox
              command:
                - /bin/sh
                - -c
                - "kubectl delete pod $(kubectl get pods -l app=node-api -o jsonpath='{.items[0].metadata.name}') --namespace sre-challenge"
          restartPolicy: OnFailure
